version: '3.8'

services:
  backend:
    image: backend-dev
    build:
      context: ./backend-go
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    container_name: backend

  frontend:
    image: frontend-dev
    build:
      context: ./frontend-react
      dockerfile: dev.Dockerfile
    environment:
      -  BACKEND_URL=/api/
    container_name: frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    container_name: reverse-proxy-lns
    depends_on:
      - frontend
      - backend